theme: jekyll-theme-minimal
title: Hinatazaka Campaign
description: Widgets for the Hinata Campaign account. Music videos with embedded lyrics and video clips with subs.
# google_analytics: k1zvmQveFzaCP4jgZsSnkxuYCllo-zmj8vHVwGsCuTw


header_pages:
  # - ice-de-breakers.md

minimal:
  social_links:
    - { platform: x, user_url: "https://x.com/hinatacampaign" }:

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at


twitter:
  username: hinatacampaign